apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-preprocessing-gpwn4di
type: Opaque
data:
  apiticket: NVl5S2JicDIyaExaOTFaRDZmTU1qcndtSWJORkNId2NwSUdpdnVkdjBzc2pONDdRdUtnZkR2THI0Z0RKMndpag== # base64