apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-preprocessing-gsogopa
type: Opaque
data:
  apiticket: WFkwUVZFcEZPZ3BpQkp3Z2hkZjdYSGdhNjlxSXVZOUJCSkx1cEJwRmV2cmZtMktEeHdWVlpBUHZVdzVFa0JySw== # base64